name: Ivan Danov
description: Learn. Keep it simple, keep it tea. Dream big.
meta_description: "My Personal Blog, Blogging about technology, dreams, startups"

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'https://idanov.github.io/'
google_analytics: 'UA-71919301-1'
disqus: false
disqus_shortname: 'ivandanov'

# Details for the RSS feed generator
url:            'https://idanov.github.io/'
author:         'Ivan Danov'
authorTwitter:  'ivandanov'

permalink:       pretty

gems:
  - jemoji

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
